name: Aqua Scanner (Shared Component)
on:
  workflow_call:
    secrets:
      AQUA_KEY:
        required: true
      AQUA_SECRET:
        required: true

jobs:
  aqua:
    runs-on: ubuntu-latest
    steps:
      # ❌ Check out the shared repo (not caller repo)
      - name: Checkout this component repo
        uses: actions/checkout@v4
        with:
          repository: fatimaworktest/ci-aqua-component   # important: self checkout
          fetch-depth: 0

      - name: Debug git info
        run: |
          echo "WORKSPACE: $GITHUB_WORKSPACE"
          git rev-parse --is-inside-work-tree || echo "No git repo"
          git remote -v || echo "No remote found"

      - name: Run Aqua Scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --scanners misconfig,vuln,secret .
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}
          AQUA_URL: https://api.dev.supply-chain.cloud.aquasec.com
          CSPM_URL: https://stage.api.cloudsploit.com
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          OVERRIDE_REPOSITORY_NAME: ${{ github.repository }}
          OVERRIDE_REPOSITORY: ${{ github.repository }}
